export const CAPACITY_MATRIX_VERSION = "2026-05-02";

export const CAPACITY_MATRIX = {
  assumptions: {
    defaultDayHours: 24,
    defaultShiftModel: "continuo",
    notes: [
      "La matriz separa capacidad teorica y restricciones operativas esperadas.",
      "Las horas de setup, limpieza y cambio deben descontarse antes de usar esta base en planeacion semanal.",
      "La capacidad real final del sistema la define el cuello de botella del periodo y no la suma simple de capacidades por etapa.",
    ],
  },
  products: [
    {
      productKey: "coffee",
      productName: "Cafe tostado molido 250 g",
      originOptions: ["Cafe con cereza", "Cafe pergamino seco", "Cafe oro"],
      periodBase: {
        operatingDaysWeek: 7,
        hoursPerDay: 24,
        shiftsPerDay: 3,
        workMode: "continuo",
      },
      subprocesses: [
        {
          code: "CF-S1",
          name: "Beneficio humedo",
          purpose: "Lleva el cafe con cereza hasta cafe lavado listo para secado.",
          bottleneckCandidate: false,
          stages: [
            {
              seq: 1,
              stageName: "Recepcion y clasificacion",
              zone: "Patio humedo",
              line: "Linea agro",
              mainEquipment: "Tolva, mesas, tinas",
              sharedEquipment: [],
              durationHours: 4,
              setupHours: 0.5,
              cleanupHours: 0.5,
              changeoverHours: 0.25,
              operatorsRequired: 3,
              supervisorsRequired: 1,
              capacityPerRun: 2400,
              capacityUnit: "kg",
              outputPerRun: 2340,
              outputUnit: "kg",
              conflictReasons: ["humedad", "patio compartido"],
            },
            {
              seq: 2,
              stageName: "Despulpado",
              zone: "Patio humedo",
              line: "Linea agro",
              mainEquipment: "Despulpadora",
              sharedEquipment: [],
              durationHours: 5,
              setupHours: 0.5,
              cleanupHours: 0.5,
              changeoverHours: 0.25,
              operatorsRequired: 2,
              supervisorsRequired: 0,
              capacityPerRun: 2340,
              capacityUnit: "kg",
              outputPerRun: 1380,
              outputUnit: "kg",
              conflictReasons: ["agua", "piso humedo"],
            },
            {
              seq: 3,
              stageName: "Fermentacion",
              zone: "Sala fermentacion",
              line: "Linea agro",
              mainEquipment: "Tanques y cajas",
              sharedEquipment: ["Sala fermentacion"],
              durationHours: 18,
              setupHours: 1,
              cleanupHours: 1,
              changeoverHours: 0.5,
              operatorsRequired: 1,
              supervisorsRequired: 1,
              capacityPerRun: 1380,
              capacityUnit: "kg",
              outputPerRun: 1350,
              outputUnit: "kg",
              conflictReasons: ["olor", "microbiologia"],
            },
            {
              seq: 4,
              stageName: "Lavado",
              zone: "Patio humedo",
              line: "Linea agro",
              mainEquipment: "Canales y tinas",
              sharedEquipment: [],
              durationHours: 3,
              setupHours: 0.25,
              cleanupHours: 0.5,
              changeoverHours: 0.25,
              operatorsRequired: 2,
              supervisorsRequired: 0,
              capacityPerRun: 1350,
              capacityUnit: "kg",
              outputPerRun: 1320,
              outputUnit: "kg",
              conflictReasons: ["agua", "salpicado"],
            },
          ],
        },
        {
          code: "CF-S2",
          name: "Secado y beneficio seco",
          purpose: "Baja humedad, estabiliza el pergamino y prepara el lote para trilla.",
          bottleneckCandidate: true,
          stages: [
            {
              seq: 5,
              stageName: "Secado",
              zone: "Area termica",
              line: "Linea secado",
              mainEquipment: "Secador",
              sharedEquipment: ["Secador"],
              durationHours: 72,
              setupHours: 2,
              cleanupHours: 2,
              changeoverHours: 1,
              operatorsRequired: 2,
              supervisorsRequired: 0,
              capacityPerRun: 1320,
              capacityUnit: "kg",
              outputPerRun: 780,
              outputUnit: "kg",
              conflictReasons: ["calor", "equipo compartido"],
            },
            {
              seq: 6,
              stageName: "Reposo de pergamino",
              zone: "Bodega intermedia",
              line: "Linea secado",
              mainEquipment: "Tolvas y pallets",
              sharedEquipment: ["Bodega intermedia"],
              durationHours: 24,
              setupHours: 0.5,
              cleanupHours: 0.5,
              changeoverHours: 0.25,
              operatorsRequired: 1,
              supervisorsRequired: 1,
              capacityPerRun: 780,
              capacityUnit: "kg",
              outputPerRun: 772,
              outputUnit: "kg",
              conflictReasons: ["espacio", "almacenamiento intermedio"],
            },
            {
              seq: 7,
              stageName: "Trilla y clasificacion",
              zone: "Area seca",
              line: "Linea seca",
              mainEquipment: "Trilladora y zarandas",
              sharedEquipment: ["Area seca"],
              durationHours: 6,
              setupHours: 0.75,
              cleanupHours: 0.5,
              changeoverHours: 0.25,
              operatorsRequired: 2,
              supervisorsRequired: 0,
              capacityPerRun: 772,
              capacityUnit: "kg",
              outputPerRun: 640,
              outputUnit: "kg",
              conflictReasons: ["polvo", "particulado"],
            },
          ],
        },
        {
          code: "CF-S3",
          name: "Tostion y empaque",
          purpose: "Genera el producto comercial final listo para venta.",
          bottleneckCandidate: false,
          stages: [
            {
              seq: 8,
              stageName: "Tueste",
              zone: "Sala termica",
              line: "Linea tostion",
              mainEquipment: "Tostadora tambor",
              sharedEquipment: ["Tostadora tambor", "Sala termica"],
              durationHours: 8,
              setupHours: 1,
              cleanupHours: 0.5,
              changeoverHours: 0.5,
              operatorsRequired: 1,
              supervisorsRequired: 0,
              capacityPerRun: 640,
              capacityUnit: "kg",
              outputPerRun: 576,
              outputUnit: "kg",
              conflictReasons: ["calor", "humo", "equipo termico"],
            },
            {
              seq: 9,
              stageName: "Reposo post-tueste",
              zone: "Sala termica",
              line: "Linea tostion",
              mainEquipment: "Tolvas de reposo",
              sharedEquipment: ["Sala termica"],
              durationHours: 12,
              setupHours: 0.5,
              cleanupHours: 0.25,
              changeoverHours: 0.25,
              operatorsRequired: 1,
              supervisorsRequired: 1,
              capacityPerRun: 576,
              capacityUnit: "kg",
              outputPerRun: 570,
              outputUnit: "kg",
              conflictReasons: ["espacio", "olor"],
            },
            {
              seq: 10,
              stageName: "Molienda",
              zone: "Sala molienda",
              line: "Linea tostion",
              mainEquipment: "Molino",
              sharedEquipment: ["Sala molienda"],
              durationHours: 4,
              setupHours: 0.5,
              cleanupHours: 0.5,
              changeoverHours: 0.5,
              operatorsRequired: 2,
              supervisorsRequired: 0,
              capacityPerRun: 570,
              capacityUnit: "kg",
              outputPerRun: 560,
              outputUnit: "kg",
              conflictReasons: ["polvo", "contaminacion cruzada"],
            },
            {
              seq: 11,
              stageName: "Empaque 250 g",
              zone: "Sala empaque",
              line: "Linea compartida",
              mainEquipment: "Llenadora, selladora y loteadora",
              sharedEquipment: ["Linea compartida", "Sala empaque"],
              durationHours: 8,
              setupHours: 1,
              cleanupHours: 0.75,
              changeoverHours: 0.75,
              operatorsRequired: 3,
              supervisorsRequired: 1,
              capacityPerRun: 2240,
              capacityUnit: "bolsas",
              outputPerRun: 2240,
              outputUnit: "bolsas",
              conflictReasons: ["capacidad compartida", "cambio de formato"],
            },
          ],
        },
      ],
    },
    {
      productKey: "cacao",
      productName: "Chocolate en tabletas",
      originOptions: ["Cacao en baba", "Cacao seco", "Nibs", "Pasta o licor de cacao"],
      periodBase: {
        operatingDaysWeek: 7,
        hoursPerDay: 24,
        shiftsPerDay: 3,
        workMode: "continuo",
      },
      subprocesses: [
        {
          code: "CH-S1",
          name: "Poscosecha",
          purpose: "Lleva el cacao en baba a grano seco y estable.",
          bottleneckCandidate: true,
          stages: [
            {
              seq: 1,
              stageName: "Recepcion y pesado",
              zone: "Patio humedo",
              line: "Linea cacao",
              mainEquipment: "Mesas y balanzas",
              sharedEquipment: [],
              durationHours: 4,
              setupHours: 0.5,
              cleanupHours: 0.5,
              changeoverHours: 0.25,
              operatorsRequired: 3,
              supervisorsRequired: 1,
              capacityPerRun: 1900,
              capacityUnit: "kg",
              outputPerRun: 1860,
              outputUnit: "kg",
              conflictReasons: ["humedad", "patio compartido"],
            },
            {
              seq: 2,
              stageName: "Fermentacion controlada",
              zone: "Sala fermentacion",
              line: "Linea cacao",
              mainEquipment: "Cajones de fermentacion",
              sharedEquipment: ["Sala fermentacion"],
              durationHours: 120,
              setupHours: 1,
              cleanupHours: 1,
              changeoverHours: 0.5,
              operatorsRequired: 1,
              supervisorsRequired: 1,
              capacityPerRun: 1860,
              capacityUnit: "kg",
              outputPerRun: 1760,
              outputUnit: "kg",
              conflictReasons: ["olor", "microbiologia", "ocupacion del espacio"],
            },
            {
              seq: 3,
              stageName: "Secado final",
              zone: "Area termica",
              line: "Linea secado",
              mainEquipment: "Secador",
              sharedEquipment: ["Secador"],
              durationHours: 72,
              setupHours: 2,
              cleanupHours: 2,
              changeoverHours: 1,
              operatorsRequired: 2,
              supervisorsRequired: 0,
              capacityPerRun: 1760,
              capacityUnit: "kg",
              outputPerRun: 980,
              outputUnit: "kg",
              conflictReasons: ["calor", "saturacion del equipo"],
            },
            {
              seq: 4,
              stageName: "Clasificacion del grano",
              zone: "Area seca",
              line: "Linea cacao",
              mainEquipment: "Zarandas y mesas",
              sharedEquipment: ["Area seca"],
              durationHours: 5,
              setupHours: 0.5,
              cleanupHours: 0.5,
              changeoverHours: 0.25,
              operatorsRequired: 2,
              supervisorsRequired: 0,
              capacityPerRun: 980,
              capacityUnit: "kg",
              outputPerRun: 940,
              outputUnit: "kg",
              conflictReasons: ["polvo", "manejo de secos"],
            },
          ],
        },
        {
          code: "CH-S2",
          name: "Transformacion primaria",
          purpose: "Convierte el grano en licor y masa refinada.",
          bottleneckCandidate: false,
          stages: [
            {
              seq: 5,
              stageName: "Tostado de nibs",
              zone: "Sala termica",
              line: "Linea cacao",
              mainEquipment: "Tostadora tambor",
              sharedEquipment: ["Tostadora tambor", "Sala termica"],
              durationHours: 8,
              setupHours: 1,
              cleanupHours: 0.5,
              changeoverHours: 0.5,
              operatorsRequired: 1,
              supervisorsRequired: 0,
              capacityPerRun: 940,
              capacityUnit: "kg",
              outputPerRun: 880,
              outputUnit: "kg",
              conflictReasons: ["mismo equipo", "calor", "humo"],
            },
            {
              seq: 6,
              stageName: "Descascarillado",
              zone: "Area seca",
              line: "Linea cacao",
              mainEquipment: "Quebradora y aventadora",
              sharedEquipment: ["Area seca"],
              durationHours: 4,
              setupHours: 0.5,
              cleanupHours: 0.5,
              changeoverHours: 0.25,
              operatorsRequired: 2,
              supervisorsRequired: 0,
              capacityPerRun: 880,
              capacityUnit: "kg",
              outputPerRun: 760,
              outputUnit: "kg",
              conflictReasons: ["polvo", "particulado"],
            },
            {
              seq: 7,
              stageName: "Molienda de nibs",
              zone: "Sala molienda",
              line: "Linea cacao",
              mainEquipment: "Molino de piedras",
              sharedEquipment: ["Sala molienda"],
              durationHours: 6,
              setupHours: 0.75,
              cleanupHours: 0.5,
              changeoverHours: 0.25,
              operatorsRequired: 2,
              supervisorsRequired: 0,
              capacityPerRun: 760,
              capacityUnit: "kg",
              outputPerRun: 720,
              outputUnit: "kg",
              conflictReasons: ["olor", "polvo"],
            },
            {
              seq: 8,
              stageName: "Refinado",
              zone: "Sala chocolate",
              line: "Linea cacao",
              mainEquipment: "Refinador",
              sharedEquipment: ["Sala chocolate"],
              durationHours: 10,
              setupHours: 0.75,
              cleanupHours: 0.5,
              changeoverHours: 0.5,
              operatorsRequired: 1,
              supervisorsRequired: 1,
              capacityPerRun: 720,
              capacityUnit: "kg",
              outputPerRun: 700,
              outputUnit: "kg",
              conflictReasons: ["polvo fino", "inocuidad"],
            },
          ],
        },
        {
          code: "CH-S3",
          name: "Chocolate y empaque",
          purpose: "Concha, moldea, enfria y empaca el producto final.",
          bottleneckCandidate: false,
          stages: [
            {
              seq: 9,
              stageName: "Conchado",
              zone: "Sala chocolate",
              line: "Linea cacao",
              mainEquipment: "Conchadora",
              sharedEquipment: ["Sala chocolate"],
              durationHours: 16,
              setupHours: 1,
              cleanupHours: 0.75,
              changeoverHours: 0.5,
              operatorsRequired: 1,
              supervisorsRequired: 1,
              capacityPerRun: 700,
              capacityUnit: "kg",
              outputPerRun: 690,
              outputUnit: "kg",
              conflictReasons: ["proceso largo", "ocupacion continua"],
            },
            {
              seq: 10,
              stageName: "Moldeo",
              zone: "Sala chocolate",
              line: "Linea cacao",
              mainEquipment: "Dosificadora y moldes",
              sharedEquipment: ["Sala chocolate"],
              durationHours: 5,
              setupHours: 0.75,
              cleanupHours: 0.5,
              changeoverHours: 0.25,
              operatorsRequired: 2,
              supervisorsRequired: 0,
              capacityPerRun: 690,
              capacityUnit: "kg",
              outputPerRun: 680,
              outputUnit: "kg",
              conflictReasons: ["sensibilidad termica"],
            },
            {
              seq: 11,
              stageName: "Enfriado",
              zone: "Tunel frio",
              line: "Linea cacao",
              mainEquipment: "Tunel de enfriado",
              sharedEquipment: ["Tunel frio"],
              durationHours: 6,
              setupHours: 0.5,
              cleanupHours: 0.5,
              changeoverHours: 0.25,
              operatorsRequired: 1,
              supervisorsRequired: 1,
              capacityPerRun: 680,
              capacityUnit: "kg",
              outputPerRun: 672,
              outputUnit: "kg",
              conflictReasons: ["balance termico"],
            },
            {
              seq: 12,
              stageName: "Empaque de tabletas",
              zone: "Sala empaque",
              line: "Linea compartida",
              mainEquipment: "Flowpack y loteadora",
              sharedEquipment: ["Linea compartida", "Sala empaque"],
              durationHours: 8,
              setupHours: 1,
              cleanupHours: 0.75,
              changeoverHours: 0.75,
              operatorsRequired: 3,
              supervisorsRequired: 1,
              capacityPerRun: 4800,
              capacityUnit: "tabletas",
              outputPerRun: 4800,
              outputUnit: "tabletas",
              conflictReasons: ["capacidad compartida", "cambio de formato"],
            },
          ],
        },
      ],
    },
    {
      productKey: "oil",
      productName: "Aceite esencial 30 ml",
      originOptions: ["Biomasa aromatica fresca", "Biomasa picada", "Aceite crudo"],
      periodBase: {
        operatingDaysWeek: 7,
        hoursPerDay: 24,
        shiftsPerDay: 3,
        workMode: "continuo",
      },
      subprocesses: [
        {
          code: "OI-S1",
          name: "Preparacion",
          purpose: "Recibe, corta y deja lista la biomasa para extraccion.",
          bottleneckCandidate: false,
          stages: [
            {
              seq: 1,
              stageName: "Recepcion de biomasa",
              zone: "Patio verde",
              line: "Linea extractos",
              mainEquipment: "Balanzas y mesas",
              sharedEquipment: [],
              durationHours: 3,
              setupHours: 0.25,
              cleanupHours: 0.25,
              changeoverHours: 0.25,
              operatorsRequired: 2,
              supervisorsRequired: 1,
              capacityPerRun: 1400,
              capacityUnit: "kg",
              outputPerRun: 1380,
              outputUnit: "kg",
              conflictReasons: ["humedad", "materia organica"],
            },
            {
              seq: 2,
              stageName: "Picado",
              zone: "Patio verde",
              line: "Linea extractos",
              mainEquipment: "Picadora",
              sharedEquipment: [],
              durationHours: 4,
              setupHours: 0.5,
              cleanupHours: 0.5,
              changeoverHours: 0.25,
              operatorsRequired: 2,
              supervisorsRequired: 0,
              capacityPerRun: 1380,
              capacityUnit: "kg",
              outputPerRun: 1320,
              outputUnit: "kg",
              conflictReasons: ["residuos vegetales"],
            },
            {
              seq: 3,
              stageName: "Carga del destilador",
              zone: "Sala destilacion",
              line: "Linea extractos",
              mainEquipment: "Destilador",
              sharedEquipment: ["Destilador", "Sala destilacion"],
              durationHours: 2,
              setupHours: 0.75,
              cleanupHours: 0.5,
              changeoverHours: 0.25,
              operatorsRequired: 2,
              supervisorsRequired: 0,
              capacityPerRun: 1320,
              capacityUnit: "kg",
              outputPerRun: 1320,
              outputUnit: "kg",
              conflictReasons: ["vapor", "ocupacion del equipo"],
            },
          ],
        },
        {
          code: "OI-S2",
          name: "Extraccion",
          purpose: "Obtiene el aceite a partir de vapor y separacion de fases.",
          bottleneckCandidate: true,
          stages: [
            {
              seq: 4,
              stageName: "Destilacion",
              zone: "Sala destilacion",
              line: "Linea extractos",
              mainEquipment: "Destilador",
              sharedEquipment: ["Destilador", "Sala destilacion"],
              durationHours: 10,
              setupHours: 1,
              cleanupHours: 1,
              changeoverHours: 0.5,
              operatorsRequired: 1,
              supervisorsRequired: 1,
              capacityPerRun: 1320,
              capacityUnit: "kg",
              outputPerRun: 14,
              outputUnit: "l",
              conflictReasons: ["calor", "vapor", "olor"],
            },
            {
              seq: 5,
              stageName: "Separacion",
              zone: "Sala destilacion",
              line: "Linea extractos",
              mainEquipment: "Decantadores",
              sharedEquipment: ["Sala destilacion"],
              durationHours: 3,
              setupHours: 0.5,
              cleanupHours: 0.5,
              changeoverHours: 0.25,
              operatorsRequired: 1,
              supervisorsRequired: 1,
              capacityPerRun: 14,
              capacityUnit: "l",
              outputPerRun: 13.4,
              outputUnit: "l",
              conflictReasons: ["olor", "sensibilidad de extractos"],
            },
            {
              seq: 6,
              stageName: "Filtrado",
              zone: "Sala extractos",
              line: "Linea extractos",
              mainEquipment: "Filtro y tanque fino",
              sharedEquipment: ["Sala extractos"],
              durationHours: 2,
              setupHours: 0.25,
              cleanupHours: 0.25,
              changeoverHours: 0.25,
              operatorsRequired: 1,
              supervisorsRequired: 0,
              capacityPerRun: 13.4,
              capacityUnit: "l",
              outputPerRun: 12.8,
              outputUnit: "l",
              conflictReasons: ["olor", "limpieza fina"],
            },
          ],
        },
        {
          code: "OI-S3",
          name: "Acondicionamiento",
          purpose: "Estabiliza, envasa y rotula la presentacion final.",
          bottleneckCandidate: false,
          stages: [
            {
              seq: 7,
              stageName: "Estabilizacion",
              zone: "Sala extractos",
              line: "Linea extractos",
              mainEquipment: "Tanque fino",
              sharedEquipment: ["Sala extractos"],
              durationHours: 8,
              setupHours: 0.5,
              cleanupHours: 0.5,
              changeoverHours: 0.25,
              operatorsRequired: 1,
              supervisorsRequired: 1,
              capacityPerRun: 12.8,
              capacityUnit: "l",
              outputPerRun: 12.6,
              outputUnit: "l",
              conflictReasons: ["estabilidad", "olor"],
            },
            {
              seq: 8,
              stageName: "Envasado 30 ml",
              zone: "Sala empaque fino",
              line: "Linea compartida",
              mainEquipment: "Llenadora de botellas",
              sharedEquipment: ["Linea compartida"],
              durationHours: 5,
              setupHours: 0.75,
              cleanupHours: 0.5,
              changeoverHours: 0.5,
              operatorsRequired: 2,
              supervisorsRequired: 0,
              capacityPerRun: 420,
              capacityUnit: "botellas",
              outputPerRun: 420,
              outputUnit: "botellas",
              conflictReasons: ["capacidad compartida", "cambio de formato"],
            },
            {
              seq: 9,
              stageName: "Etiquetado",
              zone: "Sala empaque fino",
              line: "Linea compartida",
              mainEquipment: "Etiquetadora",
              sharedEquipment: ["Linea compartida"],
              durationHours: 3,
              setupHours: 0.25,
              cleanupHours: 0.25,
              changeoverHours: 0.25,
              operatorsRequired: 2,
              supervisorsRequired: 0,
              capacityPerRun: 420,
              capacityUnit: "botellas",
              outputPerRun: 420,
              outputUnit: "botellas",
              conflictReasons: ["capacidad compartida", "cambio de formato"],
            },
          ],
        },
      ],
    },
    {
      productKey: "cream",
      productName: "Crema cosmetica en frascos",
      originOptions: ["Base cosmetica e insumos activos", "Fases preparadas", "Crema base"],
      periodBase: {
        operatingDaysWeek: 7,
        hoursPerDay: 24,
        shiftsPerDay: 3,
        workMode: "continuo",
      },
      subprocesses: [
        {
          code: "CR-S1",
          name: "Pesado y preparacion",
          purpose: "Prepara fases e insumos antes de mezcla.",
          bottleneckCandidate: false,
          stages: [
            {
              seq: 1,
              stageName: "Pesado de insumos",
              zone: "Sala cosmetica",
              line: "Linea crema",
              mainEquipment: "Balanzas y mesas",
              sharedEquipment: [],
              durationHours: 3,
              setupHours: 0.25,
              cleanupHours: 0.25,
              changeoverHours: 0.25,
              operatorsRequired: 2,
              supervisorsRequired: 1,
              capacityPerRun: 420,
              capacityUnit: "kg",
              outputPerRun: 415,
              outputUnit: "kg",
              conflictReasons: ["orden y limpieza"],
            },
          ],
        },
        {
          code: "CR-S2",
          name: "Mezcla y homogeneizacion",
          purpose: "Construye la crema base estable para acondicionamiento.",
          bottleneckCandidate: true,
          stages: [
            {
              seq: 2,
              stageName: "Fusion y homogeneizacion",
              zone: "Sala cosmetica",
              line: "Linea crema",
              mainEquipment: "Tanque mezclador",
              sharedEquipment: ["Tanque mezclador"],
              durationHours: 8,
              setupHours: 0.75,
              cleanupHours: 0.75,
              changeoverHours: 0.5,
              operatorsRequired: 2,
              supervisorsRequired: 1,
              capacityPerRun: 415,
              capacityUnit: "kg",
              outputPerRun: 404,
              outputUnit: "kg",
              conflictReasons: ["limpieza", "cambio de formula"],
            },
            {
              seq: 3,
              stageName: "Enfriado y ajuste",
              zone: "Sala cosmetica",
              line: "Linea crema",
              mainEquipment: "Tanque mezclador",
              sharedEquipment: ["Tanque mezclador"],
              durationHours: 5,
              setupHours: 0.25,
              cleanupHours: 0.5,
              changeoverHours: 0.25,
              operatorsRequired: 1,
              supervisorsRequired: 1,
              capacityPerRun: 404,
              capacityUnit: "kg",
              outputPerRun: 398,
              outputUnit: "kg",
              conflictReasons: ["temperatura", "limpieza"],
            },
          ],
        },
        {
          code: "CR-S3",
          name: "Llenado y cierre",
          purpose: "Envasa y libera la presentacion final de crema.",
          bottleneckCandidate: false,
          stages: [
            {
              seq: 4,
              stageName: "Llenado y etiquetado",
              zone: "Sala empaque fino",
              line: "Linea compartida",
              mainEquipment: "Llenadora de frascos",
              sharedEquipment: ["Linea compartida", "Sala empaque fino"],
              durationHours: 6,
              setupHours: 0.75,
              cleanupHours: 0.5,
              changeoverHours: 0.5,
              operatorsRequired: 3,
              supervisorsRequired: 1,
              capacityPerRun: 2400,
              capacityUnit: "frascos",
              outputPerRun: 2400,
              outputUnit: "frascos",
              conflictReasons: ["capacidad compartida", "cambio de formato", "sanitizacion"],
            },
          ],
        },
      ],
    },
  ],
};

export function flattenCapacityMatrix(matrix = CAPACITY_MATRIX) {
  return matrix.products.flatMap((product) =>
    product.subprocesses.flatMap((subprocess) =>
      subprocess.stages.map((stage) => ({
        productKey: product.productKey,
        productName: product.productName,
        subprocessCode: subprocess.code,
        subprocessName: subprocess.name,
        subprocessPurpose: subprocess.purpose,
        bottleneckCandidate: subprocess.bottleneckCandidate,
        operatingDaysWeek: product.periodBase.operatingDaysWeek,
        hoursPerDay: product.periodBase.hoursPerDay,
        shiftsPerDay: product.periodBase.shiftsPerDay,
        workMode: product.periodBase.workMode,
        ...stage,
      }))
    )
  );
}
